### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by mobilesoftsmith** [ijoshsmith/Wizardry#1]
I got this error when I compiled the demo and tried to launch to my real iOS device:

dyld: Library not loaded: @rpath/Wizardry.framework/Wizardry
  Referenced from: /var/mobile/Containers/Bundle/Application/C01069E5-4D6F-4787-B996-0155C1A5617E/WizardryDemo.app/WizardryDemo
  Reason: image not found

Please advice.

**Comment by ijoshsmith** [comment]
I have seen this kind of problem happen in other projects. I find Xcode's support for embedding frameworks into apps a bit flaky. Try selecting the Wizardry scheme and build that first, then select the WizardryDemo scheme and build & run. 

If that doesn't help, try removing and adding the embedded binary back into the demo project, as described here http://stackoverflow.com/a/24345546/708350

Sorry for the trouble!

**Comment by mobilesoftsmith** [comment]
Adding the wizardry.framework into General -> Embedded Binaries fixed this problem. Thanks,
