### ISSUE TITLE
How to connect to IBActions in WizardViewController

### ISSUE THREAD

**Issue by namannik** [ijoshsmith/Wizardry#4]
In `SignUpWizardViewController` in the demo, there's a note that says:

>The Back and Next bar button items are connected in the SignUpWizard storyboard to action methods defined in WizardViewController.

I'm finding that I have no idea how to connect from a xib in Interface Builder to an IBAction defined in `WizardViewController`, since the IBActions are defined in the view controller's super class, which is contained in a framework.  Can you offer any pointers on how to do this?

As a workaround, I've modified `WizardViewController` by moving the IBAction methods from an extension to directly within the main class, and changing their access from `public` to `open`.  Then, I've overridden these methods in my subclass, and these overridden methods simply call the method in the super class.  This provides access for me to be able to connect from my xib to these IBActions.  I'm not even sure if this is the right way to make this work.

**Comment by ijoshsmith** [comment]
You can use the standard IB support for hooking up actions on the right-hand pane as seen in this screenshot, or by right-clicking the view controller to bring up the list of available action methods and dragging to the bar button items from there.
![how-to](https://cloud.githubusercontent.com/assets/789832/21611727/0d2287de-d19c-11e6-84b7-c6b53f57dde9.jpg)

**Comment by namannik** [comment]
Thanks.  I had tried that, but Xcode isn't showing the "Received Actions" area for my view controller.  Perhaps it's because I'm not using storyboards.  Who knows.  Anyway, I eventually realized that I can do the same thing in code:

```
self?.backButtonItem.target = self;
self?.backButtonItem.action = #selector(self?.handleGoToPreviousStep(_:));
self?.nextButtonItem.target = self;
self?.nextButtonItem.action = #selector(self?.handleGoToNextStep(_:));
```

I'm pretty new to Swift, but I think this is the correct way to do this in code...
